
const en_EN: Record<string, string> = {
    'Selamat Datang!': "Welcome!",
    'Beranda': 'Home',
    'Tentang Kami': 'About Us',
    'Berita': 'News',
    'Masuk': 'Sign In',
    'Unduh Aplikasi': 'Download App',
    'Unduh sekarang di App Store dan Play Store.': 'Download now in App Store and Play Store.',
    'Hak cipta dilindungi': 'All rights reserved',
    'Unduh Sekarang !': 'Download Now !',
    'Hubungi Kami': 'Contact Us',
    'Ikuti kami di Instagram': "Follow us on Instagram",
    'Didukung oleh': 'Supported by',
    'Baksara Indonesia | Tentang Kami': 'Baksara Indonesia | About Us',
    'Baksara Indonesia | Berita': 'Baksara Indonesia | News',
    "Baksara Indonesia | Masuk": '"Baksara Indonesia | Sign In',
    'Perkenalkan Tim Kami': 'Meet Our Team',
    'Apa Kata Orang Tentang Baksara': 'What People Say About Baksara',
    'Sumber': 'Source',
    'Kata Sandi': 'Password',
    'Nama Pengguna': 'Username',
    'Masukkan nama pengguna anda' : 'Please enter your username',
    'Masukkan kata sandi anda' : 'Please enter your password',
    'Nama pengguna harus diisi' : 'Username is required',
    'Kata sandi harus diisi' : 'Password is required',
    'Kembali ke Atas' : 'Return to the Top',
}

export default en_EN