
const en_EN: Record<string, string> = {
    'Selamat Datang!': "Welcome!",
    'Beranda': 'Home',
    'Tentang Kami': 'About Us',
    'Fitur Kami': 'Our Features',
    'Berita': 'News',
    'Masuk': 'Sign In',
    'Unduh Aplikasi': 'Download App',
    'Unduh sekarang di App Store dan Play Store. ': 'Download now on App Store and Play Store.',
    'Hak cipta dilindungi': 'All rights reserved',
    'Unduh Baksara sekarang!': 'Download Baksara now!',
    'Hubungi Kami': 'Contact Us',
    'Ikuti kami di Instagram': "Follow us on Instagram",
    'Baksara | Tentang Kami': 'Baksara | About Us',
    'Baksara | Berita': 'Baksara | News',
    "Baksara | Masuk": '"Baksara | Sign In',
    'Perkenalkan Tim Kami': 'Meet Our Team',
    'Kata mereka tentang Baksara': 'What they say about Baksara',
    'Sumber': 'Source',
    'Kata Sandi': 'Password',
    'Nama Pengguna': 'Username',
    'Masukkan nama pengguna anda': 'Please enter your username',
    'Masukkan kata sandi anda': 'Please enter your password',
    'Nama pengguna harus diisi': 'Username is required',
    'Kata sandi harus diisi': 'Password is required',
    'Kembali ke Atas': 'Return to the Top',
    'Selengkapnya': 'Learn More',
    'Sugeng Rawuh': 'Welcome',
    'Pamawas Basa Jawa Minangka Budaya Kita': 'Observer of Javanese language as our culture',
    'Basa Jawa ora bakal luntur dening jaman merga ing kene kita wis siyap nguri-uri bebarengan karo': 'The Javanese language will not be eroded by time because we are here, who are ready to preserve it together with',
    'Tuliskan cerita anda menggunakan aksara jawa!': 'Write your story using Aksara Jawa!',
    'Kunjungi Baksara Translate!': 'Visit Baksara Translate!',
    'Mari bergerak bersama dan mewujudkan #LestariBudayaJawa ❤️': "Lets act together and make #LestariBudayaJawa happen❤️",
    'Menghadirkan budaya Jawa melalui pembelajaran bahasa Jawa. Kami berkomitmen untuk melestarikan warisan budaya ini dan membantu Anda belajar bahasa Jawa dengan lebih mudah dan menyenangkan': "Embracing Javanese culture through Javanese language learning. We are committed to preserve this cultural heritage and helping you learn Javanese language more easily and enjoyably",
    'Hai Sobat Baksara! 👋': 'Hi Baksara Friends! 👋',
    'Perkenalkan, aku Petruk.': 'I am Petruk.',
    'Mari menjelajahi Baksara bersamaku! 🚀': 'I will guide you exploring Baksara! 🚀',
    'Teman terbaikmu untuk belajar Bahasa Jawa': 'Your Best partner to learn Javanese Language',
    'Baksara adalah sebuah platform belajar bahasa Jawa yang didedikasikan untuk memperkaya pemahaman Anda tentang budaya Jawa melalui modul, kegiatan, dan latihan. 📚': 'Baksara is a Javanese language learning platform dedicated to enriching your understanding of Javanese culture through modules, activities and exercises. 📚',
    'Kami berfokus pada pengajaran dan penyebaran kekayaan bahasa Jawa dengan menghubungkan antara pembelajar dan budaya Jawa. 🌟': 'We focus on teaching and spreading the richness of the Javanese language by connecting learners and Javanese culture. 🌟',
    'Sebagai bagian dari hasil program Bangkit 2023, Baksara berhasil meraih posisi top-20 dalam Proyek Capstone berbasis Produk dan menerima dukungan inkubasi dari Google Indonesia serta Dikti Kemdikbudristek. 🏅': 'As part of the Bangkit 2023 program results, Baksara achieved a top-20 position in the Product-based Capstone Project and received incubation support from Google Indonesia and Dikti Kemdikbudristek. 🏅',
    'Baksara mendapat dukungan dari Google Indonesia, Direktorat Jenderal Pendidikan Tinggi, Institut Teknologi Sepuluh Nopember, dan Bangkit Academy yang dipimpin oleh Google, Tokopedia, Gojek, & Traveloka.': 'Baksara is highly supported by Google Indonesia, Directorate General of Higher Education, Institut Teknologi Sepuluh Nopember, and Bangkit Academy led by Google, Tokopedia, Gojek, & Traveloka.',
    'Berita Kebudayaan Jawa': 'Our Curated News',
    'Didukung Oleh': 'Fully Supported by',
    'Tentang Baksara': 'About Baksara',
    'Penggunaan Aplikasi': 'Application Usage',
    'Isi dan Metode Pembelajaran': 'Learning Content and Methods',
    'Berlangganan': 'Subscription',
    'Umum': 'General',
    'Dari Bangkit untuk Indonesia': 'From Bangkit to Indonesia',
    'Maaf, tidak ada berita yang ditemukan 😔': 'Sorry, no news found 😔',
    
}

export default en_EN