
const en_EN: Record<string, string> = {
    'Selamat Datang!': "Welcome!",
    'Beranda': 'Home',
    'Tentang Kami': 'About Us',
    'Fitur Kami' : 'Our Features',
    'Berita': 'News',
    'Masuk': 'Sign In',
    'Unduh Aplikasi': 'Download App',
    'Dapatkan sekarang di App Store dan Play Store, belajar bersama Baksara! 🚀': 'Get it now on the App Store and Play Store, learn with Baksara! 🚀',
    'Hak cipta dilindungi': 'All rights reserved',
    'Unduh Sekarang!': 'Download Now!',
    'Get in touch with us': 'Get in touch with us',
    'Ikuti kami di Instagram': "Follow us on Instagram",
    'Baksara | Tentang Kami': 'Baksara | About Us',
    'Baksara | Berita': 'Baksara | News',
    "Baksara | Masuk": '"Baksara | Sign In',
    'Perkenalkan Tim Kami': 'Meet Our Team',
    'Kata mereka tentang Baksara': 'What they say about Baksara',
    'Sumber': 'Source',
    'Kata Sandi': 'Password',
    'Nama Pengguna': 'Username',
    'Masukkan nama pengguna anda' : 'Please enter your username',
    'Masukkan kata sandi anda' : 'Please enter your password',
    'Nama pengguna harus diisi' : 'Username is required',
    'Kata sandi harus diisi' : 'Password is required',
    'Kembali ke Atas' : 'Return to the Top',
    'Selengkapnya' : 'Learn More',
    'Sugeng Rawuh' : 'Welcome',
    'Pamawas Basa Jawa Minangka Budaya Kita': 'Observer of Javanese language as our culture',
    'Basa Jawa ora bakal luntur dening jaman merga ing kene kita wis siyap nguri-uri bebarengan karo' : 'The Javanese language will not be eroded by time because we are here, who are ready to preserve it together with',
    'Tuliskan cerita anda menggunakan aksara jawa!': 'Write your story using Aksara Jawa!',
    'Kunjungi Baksara Translate!': 'Visit Baksara Translate!',
    'Mari Lestarikan Budaya Jawa dengan menjadi penutur bahasa jawa yang baik #JawaIkuKita!': "Let's preserve Javanese culture by being good Javanese speakers #JawaIkuKita!",
    'Baksara: Menghadirkan budaya Jawa melalui pembelajaran bahasa Jawa. Kami berkomitmen untuk melestarikan warisan budaya ini dan membantu Anda belajar bahasa Jawa dengan lebih mudah dan menyenangkan. Ayo bersama-sama menjaga dan merayakan kekayaan bahasa Jawa': "Baksara: Presenting Javanese culture through Javanese language learning. We are committed to preserving this cultural heritage and helping you learn Javanese more easily and enjoyably. Let's preserve and celebrate the richness of the Javanese language together",
    'Halo Bolo-Bolo': 'Hello Friends',
    'Nepangaken, jenengku Bakbolbot.': 'Introducing, my name is bakbolbot.',
    'Mari menjelajahi Baksara bersamaku!' : 'Come explore Baksara with me!',
    'Sugeng Rawuh ing Baksara!': 'Welcome to Baksara!',
    'Baksara adalah sebuah platform belajar bahasa Jawa yang didedikasikan untuk memperkaya pemahaman Anda tentang budaya Jawa melalui modul, kegiatan, dan latihan. 📚' : 'Baksara is a Javanese language learning platform dedicated to enriching your understanding of Javanese culture through modules, activities and exercises. 📚',
    'Kami berfokus pada pengajaran dan penyebaran kekayaan bahasa Jawa dengan menghubungkan antara pembelajar dan budaya Jawa. 🌟': 'We focus on teaching and spreading the richness of the Javanese language by connecting learners and Javanese culture. 🌟',
    'From Bangkit to Baksara, Baksara for Indonesia': 'From Bangkit to Baksara, Baksara for Indonesia',
    'Sebagai bagian dari hasil program Bangkit 2023, Baksara berhasil meraih posisi top-20 dalam Proyek Capstone berbasis Produk dan menerima dukungan inkubasi dari Google Indonesia serta Dikti Kemdikbudristek. 🏅': 'As part of the Bangkit 2023 program results, Baksara achieved a top-20 position in the Product-based Capstone Project and received incubation support from Google Indonesia and Dikti Kemdikbudristek. 🏅',
    'Baksara mendapat dukungan dari Google Indonesia, Direktorat Jenderal Pendidikan Tinggi, Universitas Indonesia, dan Bangkit Academy yang dipimpin oleh Google, Tokopedia, Gojek, & Traveloka.': 'Baksara is highly supported by Google Indonesia, Directorate General of Higher Education, University of Indonesia, and Bangkit Academy led by Google, Tokopedia, Gojek, & Traveloka.',
    'Berita Lokal': 'Local News',
    'Fully Supported by': 'Fully Supported by', 

}

export default en_EN